Updated link to installer, and updated so WINEARCH=win32 works correctly.

diff --git a/eve b/eve
--- a/eve
+++ b/eve
@@ -65,12 +65,13 @@ OPTIONS:
    
    Install
    -i [PREFIX]	Reinstall prefix for char	Into: ~/.Games/eve/char/[PREFIX]
-   -I Optional	Reinstall EVE - Online		DEFAULT ~/.Games/eve/Install
+   -I Use -s to define (Live or Test server)
    
    Help
    -h      This help
    
 Example:
+  eve -s SISI -I		# To install EVE - Online into a prefix for Test Server
   eve -i eveplayer 		# To install eveplayer prefix
   eve -c eveplayer -L		# To launch eveplayer with eve Launcher
   eve -c eveplayer -s SISI	# To launch eveplayer with eve Launcher for SISI (Test Server)
@@ -117,22 +118,20 @@ wineconf() {
 installprefix() {
 echo "Creating Dir"
 mkdir -p "$prefixpath" 
-cd "$prefixpath" || echo "error finding "$prefixpath""
+cd "$prefixpath" || echo "error locating "$prefixpath""
 mv "$char" "$char".old || echo "no existing, not backing up"
 WINEARCH=win32 WINEPREFIX="$prefixpath""$char" winetricks vcrun2005 vcrun2008 vcrun2010 corefonts win7
 exit 0
 }
 
 installeve() {
-echo "Creating Dir"
+echo "Creating Dir "$installpath""
 mkdir -p "$installpath"
-cd "$installpath" || echo "error finding "$installpath""
-wget -O installer.exe http://content.eveonline.com/663778/EVE_Online_Installer_663778.exe || echo "error could not find installer on EVE-Online Website, Update link location in script line 117"
+cd "$installpath" || echo "error locating "$installpath""
+wget -O installer.exe "http://content.eveonline.com//825275/EVE_Online_Installer_825275.exe" || echo "error could not find installer on EVE-Online Website, Update link location in script line 130"
 if [[ "$server" == "tranquility" ]]; then
-  mkdir "$installpath"tranquility || echo "error while creating tranquility path" && "echo test and"
   WINEARCH=win32 WINEPREFIX="$installpath"tranquility wine installer.exe
   else
-  mkdir "$installpath"singularity || echo "error while creating singularity path"
   WINEARCH=win32 WINEPREFIX="$installpath"singularity wine installer.exe
 fi
 exit 0
